#
# Takes the files generated by Webscraper.py and creates a usable dataset to train some classifier on
#


import os
import json
import pprint
import re

classes = {"wall", "wallbreaker", "sweeper", "glasscannon", "pivot", "utility", "revengekiller", "spinblocker", "stallbreaker", "tank", "support", "supporter", "trapper"}


def findkeywords(description, classes):
    description = description.replace("glass cannon", "glasscannon")
    description = description.replace("revenge killer", "revengekiller")

    words = {e for e in re.compile(r"\W+").split(description)}

    return words.intersection(classes)


files = os.listdir("pokemonListings/")
dataset = []

for file in files:
    f = open("pokemonListings/" + file, 'r')
    data = json.loads(f.read())
    f.close()

    if not data["strategies' format"] in {"OU", "UU", "RU"}:
        continue

    overviewkeywords = findkeywords(data["overview"], classes)

    for strategy in data["strategies"]:
        keywords = findkeywords(strategy["usage"], classes).union(findkeywords(strategy["name"], classes)).union(overviewkeywords)

        if len(keywords) == 0:
            continue

        featureValues = {"stats":   strategy["stats"],
                         "item":    strategy["item"],
                         "ability": strategy["ability"],
                         "type":    strategy["type"],
                         "moves":   [elem for lis in strategy["moves"] for elem in lis]
                        }

        dataset.append({"labels": [e for e in keywords],
                        "features": featureValues,
                        "name": data["name"] + " - " + strategy["name"]
                        })

f = open("dataset.json", 'w')
json.dump(dataset, f, indent=4)
f.close()
